Add crowdin file
vtex-apps/doc-prop-component pull request #1
Opened 2021-08-23 11:38 UTC by daniserejo

Add crowdin file for crowdin integration

2021-08-24 13:40 UTC, camilavcoutinho requested changes

2021-08-24 13:40 UTC, camilavcoutinho commented on CHANGELOG.md
> +### Added
```suggestion

### Added
```

2021-08-24 16:39 UTC, camilavcoutinho approved these changes

2021-09-02 14:21 UTC, juliarocha approved these changes
🚀

2021-09-08 12:27 UTC, igorbrasileiro approved these changes
Remove changelog changes and merge.

2021-09-08 12:27 UTC, igorbrasileiro commented on CHANGELOG.md
> +
```suggestion
```

2021-11-29 14:33 UTC, closed without merging